name: Type Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  type_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: pip install nox
    - name: Run type checking
      run: nox -s type_check
